# filepath: c:\Users\xblac\OneDrive\Datos adjuntos\Netward1.3\Netward1.3\.streamlit\config.toml
[theme]
primaryColor = "#0066ff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
